<?php
$shippings = $this->getShippings();
?>
<div class="container">
	<div class="row mb-3">
		<div class="col-md-6">
		<h2>Manage Shipping Method</h2>
	</div>
			<div class="col-md-6 text-end">
		<a href="<?php echo $this->getUrl('add', null , [], true);?>"class="btn btn-primary">Add Shipping Method</a>
	</div>
</div>
</div>
<table class="table table-striped table-hover text-center">
	<?php if (!$shippings): ?>
	<tr>
		<td colspan="11" align="center"><b>No data found.</b></td>
	</tr>
	<?php else: ?>
	<tr class="bg-primary bg-gradient">
		<th>Shipping Method Id</th>
		<th>Name</th>
		<th>Amount</th>
		<th>Status</th>
		<th>Created At</th>
		<th>Updated At</th>
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>
	<?php foreach ($shippings as $shipping) : ?>
	<tr>
		<td><?php echo $shipping->shipping_method_id; ?></td>
		<td><?php echo $shipping->name; ?></td>
		<td><?php echo $shipping->amount; ?></td>
		<td><?php echo $shipping->getStatusText(); ?></td>
		<td><?php echo $shipping->created_at; ?></td>
		<td><?php echo $shipping->updated_at; ?></td>
		<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $shipping->shipping_method_id]);?>"class="btn btn-sm btn-primary">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $shipping->shipping_method_id]);?>"class="btn btn-sm btn-danger">DELETE</a></td>
	</tr>
<?php endforeach; ?>
<?php endif; ?>
</table>